replicaCount: 1

ingress:
  # enabled -- Enables getting access to the application from the internet
  enabled: true
  # annotations -- Used with cert-manager to trigger cm-acme pods (certificate resolvers)
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/auth-realm: Authentication Required - 1Password
    nginx.ingress.kubernetes.io/auth-secret: basic-auth
    nginx.ingress.kubernetes.io/auth-type: basic
  hosts:
    - host: dagit.inarix.com
      serviceName: dagster-dagit
      path: /
    - host: viewer.dagit.inarix.com
      serviceName: dagster-dagit-read-only
      path: /
  tls: 
    - hosts:
        - dagit.inarix.com
      secretName: dagit-inarix-tls

image:
  repository: qdrant/qdrant
  pullPolicy: IfNotPresent
  tag: latest

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

# checks - Readiness and liveness checks can only be enabled for either rest or grpc (multiple checks not supported)
# grpc checks are only available from k8s 1.24+ so as of per default we check rest
service:
  type: ClusterIP
  annotations: {}
  ports:
    - name: rest
      port: 6333
      targetPort: 6333
      protocol: TCP
      checksEnabled: true
    - name: grpc
      port: 6334
      targetPort: 6334
      protocol: TCP
      checksEnabled: false
    - name: p2p
      port: 6335
      targetPort: 6335
      protocol: TCP
      checksEnabled: false

livenessProbe:
  enabled: true
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 1
  failureThreshold: 3
  successThreshold: 1

readinessProbe:
  enabled: true
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 1
  failureThreshold: 3
  successThreshold: 1

podAnnotations: {}

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

persistence:
  accessModes: [ "ReadWriteOnce" ]  
  size: 1Gi
  #storageClassName: local-path

#only supported for single node qdrant clusters.
snapshotRestoration:
  enabled: false
  pvcName: snapshots-pvc
  snapshots: 
  #  - /qdrant/snapshots/test_collection/test_collection-2022-10-24-13-56-50.snapshot:test_collection
  
#modification example for configuration to overwrite defaults
config:
  cluster:
    enabled: true
    p2p:
      port: 6335
    consensus:
      tick_period_ms: 100
