apiVersion: v1
kind: PersistentVolumeClaim
metadata:
name: qdrant-storage
labels:
    app: {{ template "qdrant.name" . }}
spec:
storageClassName: {{ .Values.persistence.storageClassName }} 
accessModes:
{{- range .Values.persistence.accessModes }}
    - {{ . | quote }}
{{- end }}
resources:
    requests:
    storage: {{ .Values.persistence.size | quote }} 